### PR TITLE
Implement retry policy

### LINKED ISSUE #24: Implement a retry policy
Add a capability of dealing with transient network outages via the following retry policy:

* The retry policy should be **enabled** by default.
* The following should be configurable (preferably via the `DeliveryOptions` class):
  * enable/disable the retry logic (bool)
  * maximum amount of retry attempts (int)
* If specified, the Delivery client should retry in exponential retry intervals.
* The interval, in milliseconds, is always calculated as a power of the number 2. The exponent is the ordinal number of the next attempt. The result is then multiplied by 100. The order is one-based. For instance, the first retry attempt interval equals to (2<sup>2</sup> * 100), the second equals to (2<sup>3</sup> * 100), etc.
* When all retry attempts fail, the SDK should notify the client code about it, preferable via an exception.

Just a note: Platform- or framework-specific conventions have bigger priority than keeping the implementation the same in all our projects. Therefore, the above spec does not have to be followed along strictly, should there be a convention saying otherwise.

Sample implementation in other SDKs:
- [PHP](https://github.com/Kentico/delivery-sdk-php/commit/f402059504cdc2a23ec8bf368ffdc14e8426a2af)
- [.NET](https://github.com/Kentico/delivery-sdk-net/pull/115)
- [Java](https://github.com/Kentico/delivery-sdk-java/pull/54)

### PR DESCRIPTION
**Pull request by Adoby7**
### Motivation

Which issue does this fix? Fixes #24 

### Checklist

- [x] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [x] Tests are passing
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

The automated testing for the retry policy is quite difficult as we cannot inject the http response while testing
Therefore I proposed a manual testing: 
1. Modify the `DeliveryClient` in the `CafesViewController` with a large retry number. (e.g. 20).
1. Turn off the WiFi.
1. Open the app, switch to "location" tab.
1. After 20 seconds, turn on the WiFi.
1. The page will be loaded correctly since it kept retrying getting items.

I am appreciated if you can give me some advice about automated test

### CODE REVIEW

**Comment by Adoby7** [comment]
The automated testing for the retry policy is quite difficult as we cannot inject the http response error while testing.

Therefore I proposed a manual testing, I am not sure whether it is acceptable.
Could you give me some comments @petrsvihlik ? Thank you.

**Comment by petrsvihlik** [comment]
hi @Adoby7 , thanks for the PR! @makma will get back to you soon :)

**Comment by makma** [comment]
Hi @Adoby7, I'm on it, I'm going to let you know asap!

**Comment by Adoby7** [comment]
Hi @makma , I have rewritten the retry logic with the Alamofire's Request Retrier.

**Comment by Adoby7** [comment]
Add one more test case: Suppose the max number of retry is 10. The first page retries 5 times, and success in 6-th retry. Then in the second page, the max retry number should also be 10 if network down (i.e, the max retry attempts should not be 10 - 6 = 4 times in second page)

**Pull request merged**
