### PR TITLE
[+] Add platform ios > 9.0

### PR DESCRIPTION
**Pull request by tanut2539**
### Motivation

Which issue does this fix? Fixes #`issue number`

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docu has been updated (if applicable)
- [ ] Temporary settings (e.g. project ID used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

### CODE REVIEW

**Comment by petrsvihlik** [comment]
@tanut2539 could you please adjust the description of the pull request so that it's clear what it fixes. also, the [build is failing](https://travis-ci.org/Kentico/cloud-sdk-swift/builds/435507364?utm_source=github_status&utm_medium=notification)

**Comment by makma** [comment]
The failing test is not imo caused by this PR, will investigate it internally.

**Comment by petrsvihlik** [comment]
thx @makma

**Comment by makma** [comment]
I can confirm the failing tests are caused by changed contract in Geo-location specific domain for assets feature. I'll fix the tests later this week.

**Comment by petrsvihlik** [comment]
@tanut2539 the tests have been fixed and merged to master. can you please update your branch?

**Pull request closed without merging**
