### PR TITLE
Fix: prevent usage of both preview and secured API keys together

### PR DESCRIPTION
**Pull request by sagarchoudhary96**
Fixes Issue #47 

### Checklist
- [x] Code follows coding conventions held in this repo
- [x] Add Automated Tests
- [x] Tests are passing
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

if we try initializing a client with both previews and secured API key it throws out fatalError telling that both cannot be used together.

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
thanks @makma , i'll add tests for it and update PR soon.

**Comment by sagarchoudhary96** [comment]
@makma  added test for it as per nimble docs for writing test for fatalError() `https://github.com/Quick/Nimble#swift-assertions`

**Comment by sagarchoudhary96** [comment]
@makma , will be great to get feedback on this PR.

**Comment by makma** [comment]
Hi @sagarchoudhary96, sorry for longer response time, I'm travelling a lot these days but I'm on it now. I'll let you know asap. Thank you for your understanding.

**Pull request merged**
