### PR TITLE
Add SDK tracking header

### PR DESCRIPTION
**Pull request by makma**

### CODE REVIEW

**Comment by petrsvihlik** [comment]
can't we fetch the version number somehow automatically?

**Comment by makma** [comment]
Great question - I'm not aware of any way how to natively in swift parse ruby (afaik) config where the version is specified. I can create a question on SO.

**Comment by petrsvihlik** [comment]
would be great to find out whether it's possible and how...otherwise, I'm a bit afraid that we'll be forgetting to increase the version number :)

**Comment by makma** [comment]
End of all, it's not possible to access package version while compile time - [source ](https://stackoverflow.com/questions/48440356/access-or-parse-podspec-via-swift).
It's only possible to access version of the main app (the app which is using our SDK) - [source](https://stackoverflow.com/questions/25965239/how-do-i-get-the-app-version-and-build-number-using-swift) - so we must hardcode it and change it with every new version.

**Comment by petrsvihlik** [comment]
We could try to update it in Travis...what about that?

**Comment by petrsvihlik** [comment]
it's good enough for now

**Pull request merged**
